global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using OpenHRCore.Domain.Workforce.Entities;
global using OpenHRCore.Domain.Workforce.Interfaces;
global using OpenHRCore.Domain.CareerConnect.Entities;
global using OpenHRCore.Domain.CareerConnect.Interfaces;
global using OpenHRCore.Infrastructure.Data;
global using OpenHRCore.SharedKernel.Infrastructure;
global using OpenHRCore.Infrastructure.Workforce.Repositories;